language: java

services:
  - rabbitmq
#  - postgresql

before_script:
  - rabbitmqctl add_user plantlive_rabbituser plantlive_nevertell
  - rabbitmqctl set_permissions -p / plantlive_rabbituser "" "" ".*"
  - rabbitmqctl set_user_tags plantlive_rabbituser test-consumer
  - rabbitmqadmin declare queue name=plantlive durable=true

#addons:
#  postgresql: "11"