server:
  applicationConnectors:
    - type: http
      port: 3000
  adminConnectors:
    - type: http
      port: 4000

persistence:
  type: sql
  database:
    # the name of your JDBC driver
    driverClass: org.postgresql.Driver
    # the username/password
    user: $DATABASE_USER
    password: $DATABASE_PASS

    # the JDBC URL
    url: $DATABASE_JDBC_URL

    # any properties specific to your JDBC driver:
    properties:
      charSet: UTF-8

    # the maximum amount of time to wait on an empty pool before throwing an exception
    maxWaitForConnection: 1s

    # the SQL query to run when validating a connection's liveness
    validationQuery: "/* MyService Health Check */ SELECT 1"

    # the timeout before a connection validation queries fail
    validationQueryTimeout: 3s

    # the minimum, maximum number of connections to keep open
    minSize: 8
    maxSize: 32

    # whether or not idle connections should be validated
    checkConnectionWhileIdle: false

    # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
    evictionInterval: 10s

    # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
    minIdleTime: 1 minute

in:
  type: rabbit
    host: 127.0.0.1
    port: 5672
    username: plantlive_rabbituser
    password: plantlive_nevertell
    queue: plantlive

out:
  type: http